### ISSUE TITLE
Comparison between sklearn RandomForest and ExtraTrees

### ISSUE THREAD

**Issue by sju777** [NeuroDataDesign/scikit-learn#27]
**Description**
Currently, there is no official comparison using multiple datasets between the accuracies of sklearn's RandomForest and ExtraTrees classifiers.

**Enhancement**
I will make a tutorial notebook that benchmark RFClassifier and ExtraTreesClassifier using the CC-18 and 100 datasets in OpenML. The figures that will be included are heatmaps (portraying accuracies of hyperparameter pairs), accuracies (plotted against number of features and number of samples), and runtimes (also plotted against number of features and number of samples).

**Comment by bdpedigo** [comment]
Can you briefly describe what figures/tables you plan on making (so we know how to evaluate success at end of sprint 1) ?

**Comment by sju777** [comment]
Yea! I will update the description in a few minutes.
